### ISSUE TITLE
Support SARIF export

### ISSUE THREAD

**Issue by elgohr** [zaproxy/actions-common#164]
Hey,
wouldn't it be better for GitHub actions to upload results as SARIF (https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github) instead of creating an issue?
At the moment it can get very confusing regarding the status of individual findings within the issue.
In addition this would also cover the flow of handling individual false-positives.

I found https://www.zaproxy.org/docs/desktop/addons/report-generation/report-sarif-json/ , but no way to use it within the GitHub Actions. Would be great to have it like 

```
name: "Upload SARIF"
on: ...
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://example.com/'
          sarif_file: results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: zap
```
