### ISSUE TITLE
Combine actions into one

### ISSUE THREAD

**Issue by tony** [zaproxy/actions-common#31]
To simplify maintenance it is possible to combine the 4 repositories, and allow specifying `script_name` as an input. Raise an error if `script_name` isn't found (in case someone forks with a custom script)

```yaml
steps:
  - name: ZAP Scan
    uses: zaproxy/action
    with:
      script_name: 'zap-api-scan.py'
      target: 'https://www.zaproxy.org/'
```

The `index.js` can then have a `switch` / `if` to handle differences between the scripts.

The scripting logic can then validate any specialized (script specific) inputs correctness and throw/exit as needed.

This eliminates needing to main 4 repos and keeps everything sync'd without needing to keep the common library up to date.

On the issue tracker labels can be created referring to the script.
